### ISSUE TITLE
[Suggestion] Create Abilities as constants inside main class

### ISSUE THREAD

**Issue by marceloboeira** [pagarme/ruler#3]
I think, in order to organize better the structure, you should use class constants to store the types of ability, like:

`Ability.CREATE`, `Ability.DELETE`, ... 

After that, you could use:
`acl.judge(person, Ability.CREATE, 'user').then(function(access){ ... `

I just found it less suitable for errors, you kind of let the string fixed on the constant, if by any chance you need to change the string, you'll need less effort.

**Comment by thebergamo** [comment]
Sounds good, but I don't know how good is this on JS. In rare cases I see other modules export Constatns. Feel free to implement and send the PR =D

**Comment by thebergamo** [comment]
@marceloboeira this is DONE =D

**Comment by marceloboeira** [comment]
@thebergamo sorry I didn't have the time to code it, I'm at 4 personal projects, studying and last weekend I was at the #HackInPoA. Anyway, you get the idea, perfect implementation!

**Comment by thebergamo** [comment]
Thanks =D

If you have time help me on #2 this is my big problem now hehe

Don't worries, the time is very tiny for me too. Working and Studying cosuming very much

**Comment by marceloboeira** [comment]
@thebergamo what do you want to do about it? create examples/hotsite ?
